package GameRuleLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Condition = 1;
  public static final int GameRule = 2;
  public static final int InsertAction = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7243e6ac03d84eb4L, 0x9ecc7a6ffc7a53d2L);
    builder.put(0x520310003ee1f8d9L, Action);
    builder.put(0x520310003ee1f8cdL, Condition);
    builder.put(0x520310003ee1f8beL, GameRule);
    builder.put(0x69bb4663c58e4d37L, InsertAction);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
