package GameRuleLanguage.sandbox;

/*Generated by MPS */


public class Action {
  private String id;
  public Action(String id) {
    this.id = id;
  }
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
}
